pipelines:
  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: sync-files
          script:
            - ./deploy-to-production
      - step:
          name: Update images
          deployment: update-images
          trigger: manual
          script:
            - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_REMOTE_PATH && ./update-images"
      - step:
          name: Restart server
          deployment: restart-services
          trigger: manual
          script:
            - ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_REMOTE_PATH && ./after-deploy"
