pipelines:
  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: sync-files
          script:
            - ./deploy-to-production
      - step:
          name: Restart server
          deployment: restart-services
          trigger: manual
          script:
            - ssh $DEPLOY_HOST "cd $REMOTE_PATH && ./after_deploy"
