version: '3.7'

services:
  jogowar:
    build:
      context: ./implementacao/server
      dockerfile: Dockerfile
    volumes:
      - ./implementacao/server:/app
    ports:
      - 8080:8080
    command: /app/start_game.prod.sh

  nginx:
    image: nginx:1.17.9
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
    ports:
      - 80:80

