version: '3.7'

services:
  server:
    image: ricardogpsf/jogowar:v1
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    ports:
      - "8080:8080"
      - "9092:9092"
    networks:
      - jogowar-network
    stdin_open: true
    tty: true


networks:
  jogowar-network:
    driver: bridge
