version: '3.7'

services:
  server:
    build:
      context: ./implementacao/server
      dockerfile: Dockerfile
    image: jogowar/app
    volumes:
      - ./implementacao/server:/app
    ports:
      - 8080:8080
      - 9092:9092
    networks:
      - jogowar-network
    stdin_open: true
    tty: true

networks:
  jogowar-network:
    driver: bridge
