image: atlassian/rsync-deploy:0.4.2
pipelines:
  branches:
    master:
      - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - ./deploy-to-production
      - step:
        name: Restart server
        deployment: production
        trigger: manual
        script:
          - ssh $DEPLOY_HOST "cd $REMOTE_PATH/implementacao && ./after_deploy"
